paths:
  - packages/*/Configuration/TypoScript
  - packages/*/Configuration/TSconfig
filePatterns:
  - "*.typoscript"
  - "*.tsconfig"
sniffs:
  - class: Indentation
    parameters:
      useSpaces: true
      indentPerLevel: 2
      indentConditions: true
  - class: DeadCode
  - class: OperatorWhitespace
  - class: RepeatingRValue
    parameters:
      allowedRightValues:
        - "TYPO3\\CMS\\Frontend\\DataProcessing\\DatabaseQueryProcessor"
  - class: DuplicateAssignment
  - class: EmptySection
  - class: NestingConsistency
    parameters:
      commonPathPrefixThreshold: 1
